project/apps/Cliente/urls.py
from django.urls import path
"""Include llama urls de otras apps"""
from .views import index, cliente, crear_cliente, busqueda
app_name="Cliente"
urlpatterns = [
    path("", index, name="Home" ),
    path("clientes_predeterminados/", cliente, name = "clientes"  ),
    path("crear/", crear_cliente, name="crear"),
    path("search/", busqueda, name="search")
    
]
"Cda funcion cread se le agregara una urls"

project/apps/Home/urls.py
from django.urls import path
"""Include llama urls de otras apps"""
from .views import home
app_name = "Home"
urlpatterns = [
    path("", home, name="Home" ),
    
]

project/apps/Producto/urls.py
from django.urls import path
"""Include llama urls de otras apps"""
from .views import index
app_name= "Producto"
urlpatterns = [
    path("", index, name="Home" ),
    
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
"""Include llama urls de otras apps"""
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/", include("Home.urls")),
    path("clientes/", include("Cliente.urls") ),
    path("saludar/", views.saludo),
    path("vista2/", views.segunda_vista),
    path("persona/<apellido>/<nombre>/", views.nombre),
    path("probando_templates/",views.probando_template ),
    path("notas/", views.desafio),
    path("promedio/", views.promedio),
    path("producto/",  include("Producto.urls")),
    
    
]

project/Cliente/models.py
from django.db import models

# Create your models here.
class Pais(models.Model):
    nombre = models.CharField(max_length=50)
    "Esto se usa para que nos devuelvan el tipo de datos que queremos en cada variable de clase, Charfield s campo de texto por ejemplo"
    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    nacimiento = models.DateField(null=True)
    "Este NULL=TRUE sirve para saber que este dato es opcional"
    pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True)
    "Este es un tipo de ato FK, lo recibiria como lo quisimos en su modelo local, Y el on delete sirve que para cuando esta FK se borre en su formato local nos salte Null el cliente a lque se le atribuyo"
    def __str__(self):
        return f"{self.nombre } {self.apellido}"

project/apps/Cliente/models.py
from django.db import models

# Create your models here.
class Pais(models.Model):
    nombre = models.CharField(max_length=50)
    "Esto se usa para que nos devuelvan el tipo de datos que queremos en cada variable de clase, Charfield s campo de texto por ejemplo"
    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    nacimiento = models.DateField(null=True)
    "Este NULL=TRUE sirve para saber que este dato es opcional"
    pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, blank=True)
    "Este es un tipo de ato FK, lo recibiria como lo quisimos en su modelo local, Y el on delete sirve que para cuando esta FK se borre en su formato local nos salte Null el cliente a lque se le atribuyo"
    def __str__(self):
        return f"{self.nombre } {self.apellido}"

project/apps/Home/models.py
from django.db import models

# Create your models here.

project/apps/Producto/models.py
from django.db import models

# Create your models here.

project/apps/Cliente/forms.py
from django import forms

from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ["nombre", "apellido", "nacimiento", "pais_origen_id"]
        "Valores que queremos visualizar"

project/apps/Cliente/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from datetime import date
from.models import Cliente, Pais
from .forms import ClienteForm

# Create your views here.

def index(request):
    clientes_registros = Cliente.objects.all() 
    """Esta funcion muestra los objetos de un modelo"""
    contexto = {"Clientes": clientes_registros}
    return render(request, "cliente/index.html", context=contexto)

def cliente(request):
    from datetime import date
    p1 = Pais(nombre="Peru")
    p2 = Pais(nombre="Australia")
    c1 = Cliente(nombre="Almendra", apellido="Ruiseñor", nacimiento = date(2015,1,1), pais_origen_id = p1)
    c2 = Cliente(nombre="Americo", apellido= "Rosales", nacimiento = date(2006,9,11), pais_origen_id = p2)
    p1.save()
    p2.save()
    
    c1.save()
    c2.save()

    
    "Esto sirve para guardar automaticamente datos en la base"
    return redirect("Cliente:Home")

"Funcion para crear forms"
def crear_cliente(request : HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = ClienteForm(request.POST)
        #Indiaca que esta variable debe guardarse
        if form.is_valid():
            form.save()
            return redirect("Cliente:Home")
    else: #request.method == "GET"
        form = ClienteForm()

    return render(request, "cliente/crear.html", context= {"form": form})

def busqueda(request : HttpRequest) -> HttpResponse:
    #Busqueda por nombre
    cliente_nombre = Cliente.objects.filter(nombre__contains = "Matias")
    #Buscar los que tienen un pais vacio
    cliente_pais = Cliente.objects.filter(pais_origen_id=None)
    #Busqueda por nacimiento (mayor a los 2000)
    cliente_nacimiento = Cliente.objects.filter(nacimiento__gt = date(2000,1,1))
    contexto ={"cliente_nombre":cliente_nombre,
        "cliente_nacimiento":cliente_nacimiento,
        "sin_pais": cliente_pais}
    return render(request, "cliente/search.html", contexto)

project/apps/Home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "home/index.html")

project/apps/Producto/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    contexto = {"APP": "Aplicion Producto"}
    return render(request, "producto/Producto.html", context=contexto)

project/config/views.py
from django.http import HttpResponse
#from django.template import Context, Template
from django.shortcuts import render
from datetime import datetime
def saludo(request):
    return HttpResponse("Hola Django - Coder")

def segunda_vista(request):
    return HttpResponse("<h1> Segunda Vista </h1>")

def nombre(request, nombre:str, apellido:str):
    nombre = nombre.capitalize()
    apellido = apellido.upper()
  
    return HttpResponse(f"{apellido}, {nombre}")

def probando_template(request):
    #mi_html = open("./templates/template1.html")
    #mi_template= Template(mi_html.read())
    #mi_html.close()
    nombre = "Matias"
    apellido = "Landoni"
    ahora = datetime.now().strftime(r"%d/%m/%Y")
    mis_datos = {"Nombre" : nombre, "Apellido" : apellido} 
    mis_datos["Fecha"]= ahora
    #mi_contexto = Context(mis_datos)
    #mi_documento= mi_template.render(mi_contexto)
    #return HttpResponse(mi_documento)
    return render(request, "template1.html", context=mis_datos)

notas = [6, 7, 5, 10, 9, 9, 8]
def desafio(request):
    mis_notas= notas
    contexto= {"Notas": mis_notas}
    return render(request, "notas.html", context=contexto)

def promedio(request):
    suma = sum(notas)
    
    Promedio = suma / len(notas)
    contexto = {"Promedio": Promedio}
    return render(request, "template2.html", context=contexto)
    

project/apps/Cliente/templates/cliente/crear.html
{% extends "Home/base.html" %}
{% block TITULO %}
  Crear Cliente
{% endblock TITULO %}

{% block CONTENIDO %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button type="submit">Guardar Usuario</button>

</form>


<a href="{% url "Home:Home"%}"> Volver al Menu</a>
{% endblock CONTENIDO %}

project/apps/Cliente/templates/cliente/index.html
{% extends 'Home/base.html' %}

    
    {% block CONTENIDO %}
        {% for cliente in Clientes %}
            <p>{{ cliente.nombre }} </p>
            <p> {{ cliente.apellido }}</p>
            <p> {{ cliente.pais_origen_id }}</p>
        {% endfor %}
        <a href="{% url "Home:Home"%}"> Volver al Menu</a>
    {% endblock CONTENIDO %}
 

project/apps/Cliente/templates/cliente/search.html
{% extends "Home/base.html" %}
{% block TITULO %}
  Buscar Cliente
{% endblock TITULO %}

{% block CONTENIDO %}
<div>
    {% for cliente in cliente_nombre %}
       <h2>{{ cliente.nombre }}</h2>
       <p>{{ cliente.apellido }}</p>
       <p>{{ cliente.nacimiento }}</p>
    {% endfor %}
    <h3>Cliente Nacidos despues del 2000</h3>
    {% for cliente in cliente_nacimiento %}
       <p> {{ cliente }}</p>
    {% endfor %}
    <h2>Clientes sin pais</h2>
    {% for cliente in sin_pais %}
       <p> {{ cliente }}</p>
    {% endfor %}

</div>

<a href="{% url "Home:Home"%}"> Volver al Menu</a>
{% endblock CONTENIDO %}

project/apps/Home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="color: red; background-color:aqua;">
       {%  block TITULO %}
        Bienvenido a mi proyecto de Django
       {% endblock TITULO %}
    </h1>
    
    <div style="text-align: center; font-size:larger;">
    {% block CONTENIDO %}
            
    {% endblock CONTENIDO %}
    </div>
</body>
</html>

project/apps/Home/templates/home/index.html
{% extends 'Home/base.html' %} 
{% block CONTENIDO %}
    <a href="{% url "Cliente:Home"%}"> Ir a Clientes</a>
    <a href="{% url "Producto:Home"%}"> Ir a Productos</a>
{% endblock CONTENIDO %}

project/apps/Producto/templates/producto/Producto.html
{% extends 'Home/base.html' %}
{% block TITULO %}
    <p>{{ APP }}</p>
{% endblock TITULO %}

{% block CONTENIDO %}
    <a href="{% url "Home:Home"%}> Volver al Menu</a>
    
{% endblock CONTENIDO %}

project/templates/notas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Mis Notas</h1>
    
    <div> 
        <h4>Primer Trimestre</h4>
        <ul>
            {% for Nota in Notas%}
                {% if Nota < 6 %}
                   <li style="list-style: none;">{{Nota}} = Mala Nota</li>
                   {% else %}
                   <li style="list-style: none;"> Prueba 1: {{ Nota }}</li>
                   
                {%endif%}
            {%endfor%}
        </ul>
    </div>
</body>
</html>

project/templates/template1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hola Mundo</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At quibusdam sed magnam cumque cum ducimus repellat nisi nesciunt, tempora cupiditate temporibus corrupti possimus unde dolor eaque, facere quae eum aliquid?</p>
    <h2 style="background-color: aqua;">Nombre: {{ Nombre }}</h2>
    <h2 style="color: red;">Apellido: {{ Apellido }}</h2>
    <h6> Fecha y Hora: {{ Fecha }}</h6>
</body>
</html>

project/templates/template2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Promedio de tus Notas</h1>
    < <ul>
        {% for Nota in Notas%}
               <li style="list-style: none;"> Notas: {{ Nota }}</li>
        {%endfor%}
        <h3>Promedio = {{ Promedio }}</h3>
    </ul>
</body>
</html>